
---
server:
  port: 8090
spring:
  profile: prod
  datasource:
    platform: postgres
  jpa:
    show-sql: true
    generate-ddl: true
    database: POSTGRESQL

management:
 endpoints:
   web:
     cors:
      allowed-origins: '*'
      allowed-methods: GET,POST
     exposure:
       include: beans,env,metrics

logging:
  level:
    root: INFO

---
spring:
  profiles: dev
server:
  port: 8090