
server:
  port: 8090
spring:
  jpa:
    generate-ddl: true
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/documents
    username: richard
    password: test123
    driver-class-name: org.postgresql.Driver

management:
 endpoints:
   web:
     cors:
      allowed-origins: '*'
      allowed-methods: GET,POST
     exposure:
       include: beans,env,metrics

logging:
  level:
    root: INFO
