server:
  port: 8090
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    database: POSTGRESQL
management:
 server: 127.0.0.1
 port: 8091
 endpoints:
   web:
     exposure:
       include: beans,env,metrics

logging:
  level:
    root: INFO
